docs: Update instructions after slack action v2 update
grafana/shared-workflows pull request #658
Opened 2024-12-17 11:11 UTC by dsotirakis

Update instructions based on: https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0

2025-01-08 11:51 UTC, zerok requested changes

2025-01-08 11:51 UTC, zerok commented on actions/send-slack-message/README.md
> +          method: post.update
```suggestion
          method: chat.update
```

2025-01-08 11:51 UTC, zerok commented on actions/send-slack-message/README.md
>            update-ts: ${{ steps.slack.outputs.ts }}
This belongs as "ts" field into the payload 🙂 
https://github.com/slackapi/slack-github-action?tab=readme-ov-file#updating-a-message

2025-01-08 11:51 UTC, zerok commented on actions/send-slack-message/action.yaml
>          update-ts: ${{ inputs.update-ts }}
This one is now part of the payload

2025-01-08 11:51 UTC, zerok commented on actions/send-slack-message/action.yaml
>          method: chat.postMessage
```suggestion
        method: ${{ inputs.method }}
```

2025-01-10 09:17 UTC, dsotirakis commented on actions/send-slack-message/README.md
> +| `update-ts`         | String | The timestamp of the message to update.                                                                                                            |
removed all update-ts bits now :)

2025-01-10 09:19 UTC, zerok approved these changes

2025-01-10 09:23 UTC, merged